Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAGLA',15,'14580023',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHEA',2,'506887',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHEA',3,'BHAHEA',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHEA',8,'584',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHEA',10,'INE565C01010',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHEA',11,'8883',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHEA',15,'12610001',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOS',2,'512608',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOS',3,'BHANDARI',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOS',8,'4372',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOS',10,'INE474E01029',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOS',11,'10746',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOS',15,'16080006',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOT',1,'BHARATHOT',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOT',2,'508984',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOT',3,'BHARATHOT',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOT',5,'bhho',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOT',7,'429','EQ');
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOT',8,'1400',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOT',9,'313',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOT',10,'INE466A01015',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOT',11,'7713',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAHOT',15,'16560011',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAIMM',2,'524663',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAIMM',3,'BHAIMM',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAIMM',8,'4148',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAIMM',10,'INE994B01014',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAIMM',11,'9685',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAIMM',15,'12540188',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAIN ',2,'519349',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAIN ',8,'3644',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAIN ',11,'12140',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BILLI ',2,'526853',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BILLI ',3,'BHAIND',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BILLI ',8,'4735',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BILLI ',10,'INE986A01012',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BILLI ',11,'7983',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BILLI ',15,'14590099',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAINT',1,'BIL',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAINT',2,'526666',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAINT',3,'BIL',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAINT',7,'7848','EQ');
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAINT',8,'4418',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAINT',9,'2860',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAINT',10,'INE828A01016',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAINT',11,'7976',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAINT',15,'16520037',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAINV',2,'501146',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHAINV',11,'10831',null);
Insert into sem_stck_map (SEM_STCK_CD,SEM_ENTTY,SEM_MAP_VL,SEM_XCHNG_SERIES) values ('BHALEA',2,'511698',null);
